name: Scrape latest data

on:
  schedule:
    - cron: '*/5 * * * *'   # Runs every 6 hours
  workflow_dispatch:

jobs:
  scheduled:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2
        with:
            persist-credentials: true
        
      - name: Fetch latest data
        run: |-
          # Fetch the air quality data
          curl -k https://www.energex.com.au/static/Energex/energex_po_current_unplanned.geojson > energex-unplanned.geojson
          curl -k https://www.energex.com.au/static/Energex/energex_po_current_planned.geojson > energex-planned.geojson
          curl -k https://www.energex.com.au/api/outages-text/v1.0.ex/summary > energex-summary.json
          curl -k https://www.energex.com.au/api/outages-text/v1.0.ex/suburb?council=&suburb= > energex-summary-suburbs.json
          curl -k https://www.ergon.com.au/static/Ergon/ergon_po_current_unplanned.geojson > ergon-unplanned.geojson
          curl -k https://www.ergon.com.au/static/Ergon/ergon_po_current_planned.geojson > ergon-planned.geojson
      
      - name: Commit and push if it changed
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git pull --rebase
          git push
